OpenSlide.Cs.WebApp/Controllers/SlideSetController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OpenSlide.Cs.WebApp.Models;
using static OpenSlide.Cs.WebApp.Models.DefaultOptions;
using Controller = Microsoft.AspNetCore.Mvc.Controller;

namespace OpenSlide.Cs.WebApp.Controllers
{
	public class SlideSetController : Controller
	{
		private const string NoAccessAlertText = "No access to data.";
		private readonly SlideSet slideSet;

		public SlideSetController()
		{
			var openSlideSupportedExtensions = new[]
			{
				"svs", "tif", "vms", "vmu", "ndpi", "scn", "mrxs",
				"tiff", "svslide", "bif"
			};
			const string mainPath = @"data";

			var dirs = FilterFiles(mainPath, openSlideSupportedExtensions);
			slideSet = new SlideSet(dirs);
		}

		public IEnumerable<string> FilterFiles(string path, params string[] exts)
		{
			return
				Directory
					.EnumerateFiles(path, "*.*")
					.Where(file => exts.Any(x => file.EndsWith(x, StringComparison.OrdinalIgnoreCase)));
		}

		public IActionResult Index()
		{
			HttpContext.Session.Remove("Slide");
			return View(slideSet);
		}

		[Microsoft.AspNetCore.Mvc.Route("[controller]/{slug}")]
		public IActionResult ViewSlide(string slug)
		{
			try
			{
				var currentSlide = slideSet.Get(slug);
				HttpContext.Session.SetString("Slide", slug);
				return View(currentSlide);
			}
			catch (Exception)
			{
				HttpContext.Session.SetString("AlertText", NoAccessAlertText);
				return RedirectToAction("Index");
			}
		}

		// GET: slug.dzi
		[Produces("application/xml")]
		[Microsoft.AspNetCore.Mvc.Route("[controller]/{slug}.dzi")]
		[OutputCache(Duration = 120, Location = OutputCacheLocation.Server)]
		public string Dzi(string slug)
		{
			try
			{
				return slideSet.Get(slug).DeepZoomGenerator.GetDziMetadataString(DEEPZOOM_FORMAT);
			}
			catch (Exception)
			{
				HttpContext.Session.SetString("AlertText", NoAccessAlertText);
				RedirectToAction("Index");
				return "";
			}
		}

		[Produces("image/jpeg")]
		[Microsoft.AspNetCore.Mvc.Route("[controller]/{slug}_files/{level:int}/{col:int}_{row:int}.jpeg")]
		[OutputCache(Duration = 120, Location = OutputCacheLocation.Server)]
		public IActionResult Tile(string slug, int level, int col, int row)
		{
			try
			{
				var slide = slideSet.Get(slug);
				var tile = slide.DeepZoomGenerator.GetTile(level, new LevelSize(col, row));

				using (var stream = new MemoryStream())
				{
					tile.Save(stream, ImageFormat.Jpeg);
					tile.Dispose();
					return File(stream.ToArray(), "image/jpeg");
				}
			}
			catch (OpenSlideException)
			{
				throw new HttpException(404, "Wrong level or coordinates");
			}
		}

		[Microsoft.AspNetCore.Mvc.Route("[controller]/{slug}/Properties")]
		public IActionResult Properties(string slug)
		{
			try
			{
				return View(slideSet.Get(slug));
			}
			catch (Exception)
			{
				HttpContext.Session.SetString("AlertText", NoAccessAlertText);
				return RedirectToAction("Index");
			}
		}

		[Microsoft.AspNetCore.Mvc.Route("[controller]/{slug}/AssociatedImages")]
		public IActionResult AssociatedImages(string slug)
		{
			try
			{
				return View(slideSet.Get(slug));
			}
			catch (Exception)
			{
				HttpContext.Session.SetString("AlertText", NoAccessAlertText);
				return RedirectToAction("Index");
			}
		}

		[Microsoft.AspNetCore.Mvc.Route("[controller]/{slug}/AssociatedImages/{imageName}")]
		[Produces("image/jpeg")]
		public IActionResult GetAssociatedImage(string slug, string imageName)
		{
			try
			{
				var slide = slideSet.Get(slug);
				var associated = slide.AssociatedImages[imageName];
				var associatedBitmap = associated.ToBitmap();
				using (var stream = new MemoryStream())
				{
					associatedBitmap.Save(stream, ImageFormat.Jpeg);
					associatedBitmap.Dispose();
					return File(stream.ToArray(), "image/jpeg");
				}
			}
			catch (Exception)
			{
				HttpContext.Session.SetString("AlertText", NoAccessAlertText);
				return RedirectToAction("Index");
			}
		}
	}
}

OpenSlide.Cs.WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using static OpenSlide.Cs.WebApp.HtmlHelperExtensions
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - OpenSlide C#</title>

	<environment names="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
		<link rel="stylesheet" href="~/css/site.css" />
	</environment>
	<environment names="Staging,Production">
		<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
			  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
			  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
		<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
	</environment>
	@Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a asp-area="" asp-controller="SlideSet" asp-action="Index" class="navbar-brand">OpenSlide Viewer</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li class="@Html.IsActive("SlideSet","Index")">
						<a asp-area="" asp-controller="SlideSet" asp-action="Index">Slides</a>
					</li>
					<li class="@Html.LinkStatus("SlideSet", "Properties", Context.Session.GetString("Slide"))">
						<a asp-area="" asp-controller="SlideSet" asp-action="Properties">Properties</a>
					</li>
					<li class="@Html.LinkStatus("SlideSet","AssociatedImages", Context.Session.GetString("Slide"))">
						<a asp-area="" asp-controller="SlideSet" asp-action="AssociatedImages">Associated Images</a>
					</li>

				</ul>
			</div>
		</div>
	</nav>
	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; AGasinsk 2017 - OpenSlide Cs# WebApp</p>
		</footer>
	</div>

	<environment names="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
	</environment>
	<environment names="Staging,Production">
		<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
				asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
				asp-fallback-test="window.jQuery"
				crossorigin="anonymous"
				integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
		</script>
		<script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
				asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
				crossorigin="anonymous"
				integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
		</script>
		<script src="~/js/site.min.js" asp-append-version="true"></script>
	</environment>

	@RenderSection("Scripts", required: false)
</body>
</html>